# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json tsconfig.json prepend-shebang.cjs .env.example ./
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY src ./src
COPY .env.example .

# Build the application
RUN npm run build

# Expose default port
EXPOSE 3000

# Default command to start MCP server
CMD ["node", "build/index.js"]
